### ISSUE TITLE
v2.1.1 cant launch cause it cant identify .NET on my computer

### ISSUE THREAD

**Issue by sakurayang** [Haato3o/HunterPie-v2#111]
### problem

as the title said.

---

### steps

here is the screenshot of v2.1.0 after launch, it can work normally

![image](https://user-images.githubusercontent.com/11017232/177861904-4fadd6fd-6df3-4163-bfc5-ec5b721bae09.png)

1. download a fresh pack from the Github release of v2.1.1
2. delete v2.1.0 files after backup it.
3. put v2.1.1 in the exact location.
4. click HunterPie.exe ...

![image](https://user-images.githubusercontent.com/11017232/177862592-9288b97c-f140-41aa-b70e-7d1e617b3390.png)

...and it just cant launch

---

### try

- try to install .net 5.0.0 instead of 5.0.17, not work
- try to move into another folder, not work
- restart my computer, not work
- run HunterPie as administrator, not work 
- run both game and HunterPie as administrator, not work
- run HunterPie before the game launch, not work
- run HunterPie after the game launch, not work

---

### environments

CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.60 GHz
RAM: 8G
OS: Win10 21H2 (19044.1766)
Windows Feature Experience Pack 120.2212.4180.0
.NET Desktop Runtiome: 5.0.0

**Comment by Haato3o** [comment]
Hmm, there hasn't been any changes to the .NET version HunterPie requires between v2.1.0 and v2.1.1, also, the popup saying it requires .NET isn't handled by HunterPie thing, that's handled by the .NET environment itself, so if it's saying it couldn't find the required version, then there's a very high chance the required version isn't installed correctly.

Try installing this version of [.NET 5.0 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.13-windows-x64-installer).

If that doesn't work, open your cmd and run the following command and paste the results here:
```sh
dotnet --list-runtimes
```

**Comment by sakurayang** [comment]
```
> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Haato3o** [comment]
It still gives you the same error?

**Comment by Haato3o** [comment]
Also, have you, by any chance, deleted the file `HunterPie.runtimeconfig.json` from your HunterPie's folder?

**Comment by sakurayang** [comment]
no, it still gives me the same error, I close my antivirus and do what I do above again, still doesn't work.

and here is the files.

![image](https://user-images.githubusercontent.com/11017232/178033786-1149334c-4188-46ce-8e5c-979fd2320768.png)

**Comment by Haato3o** [comment]
I can't really think of anything then, really looks like a computer issue considering that:

1. The .NET popup isn't handled by HunterPie
2. I haven't really seen anyone else having the same issue

There's also no difference between v2.1.1 and v2.1.0 in terms of what .NET it is using, the version is controlled by the `HunterPie.runtimeconfig.json` file, which is something that is generated by VS Studio when I compile the project. You can try opening it and changing the version to something else and see if that fixes the issue, but I can't think of anything else.

Also, have you tried letting it self-update instead of manually downloading the newest version? Manually downloading files isn't recommended as it is never 100% updated, hotfixes aren't uploaded to GitHub's releases.

**Comment by sakurayang** [comment]
yeeeee… I think is a computer issue, too.

and  because auto update will also appear this question, I turn to manually download.

I haven't tried on other computer cause some reason, so we just think it's my computer question.

**Comment by EntityAdam** [comment]
I ran into this issue as well. This is simply because .NET 5 has passed its EOL in May 2022, new users cannot install the .NET 5 runtime.

If I have time I'll try to get a PR in, upgrade to NET 6 should be a nothing task.

**Comment by Haato3o** [comment]
That's not true though, just because .NET 5.0 is no longer supported by Microsoft, doesn't mean people can no longer install it or that the runtime will simply stop working. It just means .NET 5.0 will not receive updates or security patches. 
You can still find it to download [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer). But yeah, I've been planning to upgrade to NET 6.0 anyways, in fact I've been testing it for `v2.2.0` release to see if everything is working properly. The main issue of upgrading it is that 6.0 is fairly new and not everyone has it by default and will definitely create more problems about people not installing the right version.
